pluginManagement {
    repositories {
        maven { url = 'https://maven.fabricmc.net/' }
        maven { url = 'https://maven.neoforged.net/releases/' }
        gradlePluginPortal()
        mavenCentral()
    }
}

rootProject.name = 'opsucht-chat'
include 'core'
include 'platforms:fabric'
include 'platforms:neoforge'
